/* ══════════════════════════════════════════════════════════════
   QUI SE CONNAÎT LE MIEUX ? — Affirmations Vrai / Faux
   Format : { q: "...{name}..." }
   ══════════════════════════════════════════════════════════════ */

const DUO_QUESTIONS = [

  // ── Goûts & Préférences ──────────────────────────────────────
  { q: "{name} préfère le café au thé" },
  { q: "{name} aime dormir avec une couette en été" },
  { q: "{name} préfère la plage à la montagne" },
  { q: "{name} mange souvent de la viande" },
  { q: "{name} aime les films d'horreur" },
  { q: "{name} préfère les chats aux chiens" },
  { q: "{name} aime voyager seul(e)" },
  { q: "{name} préfère l'hiver à l'été" },
  { q: "{name} mange épicé sans problème" },
  { q: "{name} préfère les sports d'équipe aux sports individuels" },
  { q: "{name} aime faire la grasse matinée le week-end" },
  { q: "{name} préfère cuisiner plutôt que commander à manger" },
  { q: "{name} boit de l'alcool lors des soirées" },
  { q: "{name} aime nager dans la mer" },
  { q: "{name} préfère le chocolat noir au chocolat au lait" },
  { q: "{name} aime regarder des séries plutôt que des films" },
  { q: "{name} préfère les vacances à l'étranger aux vacances en France" },

  // ── Habitudes & Personnalité ─────────────────────────────────
  { q: "{name} se lève avant 8h même le week-end" },
  { q: "{name} relit ses messages avant de les envoyer" },
  { q: "{name} a déjà pleuré devant un film d'animation" },
  { q: "{name} parle aux animaux comme à des humains" },
  { q: "{name} laisse toujours sa chambre en désordre" },
  { q: "{name} chante sous la douche" },
  { q: "{name} a peur du noir quand il est seul(e)" },
  { q: "{name} mange ses frites une par une" },
  { q: "{name} fait semblant d'avoir lu un livre qu'il/elle n'a pas lu" },
  { q: "{name} se parle à voix haute quand il/elle est seul(e)" },
  { q: "{name} évite les conflits à tout prix" },
  { q: "{name} oublie les anniversaires de ses proches" },
  { q: "{name} dort avec une peluche ou un coussin particulier" },
  { q: "{name} rit à ses propres blagues avant la chute" },
  { q: "{name} vérifie plusieurs fois qu'il/elle a bien fermé la porte" },
  { q: "{name} a déjà menti pour esquiver une sortie" },

  // ── Pop culture & Style de vie ───────────────────────────────
  { q: "{name} a déjà bingé une série en une nuit" },
  { q: "{name} connaît les paroles d'une chanson embarrassante" },
  { q: "{name} a déjà pleuré devant un film" },
  { q: "{name} préfère les films d'action aux comédies romantiques" },
  { q: "{name} scroll TikTok plus d'une heure par jour" },
  { q: "{name} a déjà posté puis supprimé une photo" },
  { q: "{name} met son téléphone en silencieux la nuit" },
  { q: "{name} a déjà acheté quelque chose par impulsion" },
  { q: "{name} économise de l'argent chaque mois" },
  { q: "{name} a déjà eu le cœur brisé" },
  { q: "{name} croit encore à l'amour au premier regard" },
  { q: "{name} a un rêve qu'il/elle n'a jamais avoué" },
  { q: "{name} veut vivre dans une autre ville un jour" },
  { q: "{name} préfère les podcasts à la musique en voiture" },
  { q: "{name} a déjà googlé son ex" },
  { q: "{name} pense qu'il/elle pourrait survivre sans réseaux sociaux" },

  // ── Questions Générales / Personnalité ───────────────────────

  { q: "{name} aime les activités de plein air" },
  { q: "{name} a déjà chanté sous la douche" },
  { q: "{name} préfère les films d'horreur aux films comiques" },
  { q: "{name} a un animal de compagnie" },
  { q: "{name} fait du sport régulièrement" },
  { q: "{name} est plutôt introverti(e)" },
  { q: "{name} aime voyager" },
  { q: "{name} est plus du matin que du soir" },
  { q: "{name} préfère passer son temps seul(e) plutôt qu'avec des gens" },
  { q: "{name} sait cuisiner" },
  { q: "{name} a déjà fait du bénévolat" },
  { q: "{name} préfère les vacances à la mer plutôt qu'à la montagne" },
  { q: "{name} est souvent stressé(e)" },
  { q: "{name} sait jouer d'un instrument de musique" },
  { q: "{name} a déjà pris des cours de danse" },
  { q: "{name} aime les animaux exotiques" },
  { q: "{name} a des talents cachés" },
  { q: "{name} a déjà fait un road trip" },
  { q: "{name} parle plusieurs langues" },
  { q: "{name} est passionné(e) par l'histoire" },

  // ── Relations Amicales ────────────────────────────────────────

  { q: "{name} fait confiance facilement aux autres" },
  { q: "{name} a plus de proches amis que de simples connaissances" },
  { q: "{name} croit que l'amitié entre un homme et une femme peut être purement platonique" },
  { q: "{name} préfère passer du temps avec ses amis plutôt qu'avec sa famille" },
  { q: "{name} a déjà eu une dispute avec un(e) ami(e) qu'il/elle n'a jamais réglée" },
  { q: "{name} est une personne très loyale envers ses amis" },
  { q: "{name} croit que les amis peuvent trahir" },
  { q: "{name} aime organiser des soirées entre amis" },
  { q: "{name} se confie facilement à ses amis" },
  { q: "{name} pense que l'amitié est plus importante que l'amour romantique" },
  { q: "{name} n'aime pas les conflits dans une amitié" },
  { q: "{name} a déjà fait une surprise à un(e) ami(e)" },
  { q: "{name} s'entend bien avec les amis de son/sa partenaire" },
  { q: "{name} a déjà partagé un secret qu'il/elle regrette" },
  { q: "{name} préfère les petites réunions aux grandes fêtes" },
  { q: "{name} apprécie les conversations profondes avec ses amis" },
  { q: "{name} a déjà perdu un(e) ami(e) à cause d'une incompréhension" },
  { q: "{name} se sent parfois seul(e) même entouré(e) de ses amis" },

  // ── Relations Amoureuses ──────────────────────────────────────

  { q: "{name} croit au coup de foudre" },
  { q: "{name} est déjà tombé(e) amoureux(se) de quelqu'un qui ne le/la aimait pas en retour" },
  { q: "{name} est pour les relations à distance" },
  { q: "{name} préfère une relation sérieuse à une relation informelle" },
  { q: "{name} se voit avoir des enfants un jour" },
  { q: "{name} aimerait se marier un jour" },
  { q: "{name} croit que l'amour à première vue existe vraiment" },
  { q: "{name} est du genre à faire des compromis dans une relation" },
  { q: "{name} est jaloux(se) dans une relation amoureuse" },
  { q: "{name} a déjà caché quelque chose à son/sa partenaire" },
  { q: "{name} a déjà fait une déclaration d'amour" },
  { q: "{name} croit qu'il faut être amis avant d'être en couple" },
  { q: "{name} aime recevoir des surprises romantiques" },
  { q: "{name} a déjà trompé un(e) partenaire" },
  { q: "{name} pense que l'amour peut surmonter tous les obstacles" },
  { q: "{name} est du genre à planifier l'avenir avec son/sa partenaire" },

  // ── Famille ───────────────────────────────────────────────────

  { q: "{name} s'entend bien avec ses parents" },
  { q: "{name} a des frères et sœurs" },
  { q: "{name} est plus proche de sa mère que de son père" },
  { q: "{name} a déjà eu des conflits importants avec sa famille" },
  { q: "{name} passe beaucoup de temps avec sa famille" },
  { q: "{name} a des traditions familiales" },
  { q: "{name} aimerait avoir une grande famille" },
  { q: "{name} préfère passer Noël en famille plutôt qu'avec des amis" },
  { q: "{name} partage souvent des choses personnelles avec sa famille" },
  { q: "{name} a déjà menti à sa famille pour éviter des conflits" },
  { q: "{name} aime quand sa famille organise des événements" },
  { q: "{name} voit souvent ses cousins et cousines" },
  { q: "{name} fait souvent des vacances en famille" },
  { q: "{name} pense que la famille est la chose la plus importante dans la vie" },
  { q: "{name} aimerait être plus proche de certains membres de sa famille" },
  { q: "{name} croit que la famille est toujours là pour soutenir" },

  // ── Vie Personnelle & Hobbies ─────────────────────────────────

  { q: "{name} aime lire des livres" },
  { q: "{name} est plutôt une personne créative" },
  { q: "{name} a un passe-temps qu'il/elle pratique régulièrement" },
  { q: "{name} passe plus de temps sur son téléphone que dans la vraie vie" },
  { q: "{name} apprécie les soirées Netflix" },
  { q: "{name} préfère les soirées tranquilles à la maison plutôt que de sortir" },
  { q: "{name} écrit parfois dans un journal intime" },
  { q: "{name} aime suivre les tendances" },
  { q: "{name} fait attention à sa santé mentale" },
  { q: "{name} a déjà essayé un nouveau hobby qui l'a surpris(e)" },
  { q: "{name} préfère les films d'animation aux films en prise de vue réelle" },
  { q: "{name} a un style vestimentaire qui le/la distingue des autres" },
  { q: "{name} aime prendre des photos" },
  { q: "{name} a une routine bien définie chaque jour" },
  { q: "{name} écoute souvent de la musique" },
  { q: "{name} est du genre à vivre dans l'instant présent" },
  { q: "{name} est une personne perfectionniste" },
  { q: "{name} préfère écrire plutôt que parler" },
  { q: "{name} est organisé(e) dans sa vie quotidienne" },
  { q: "{name} est ouvert(e) à essayer de nouvelles choses dans sa vie" }

];
